# Generated by Django 5.1.5 on 2025-01-23 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='media/player_photo/default_player.png', upload_to='player_photo/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
    ]
