# Generated by Django 5.1.5 on 2025-01-23 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_otp_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='player_photo/default_player.png', upload_to='player_photo/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
    ]
