# Generated by Django 5.1.5 on 2025-01-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PLAYER', 'Player'), ('MANAGER', 'Manager')], default='Player', max_length=25),
        ),
    ]
