# Generated by Django 5.1.5 on 2025-01-24 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_invitedmanager_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedmanager',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 24, 8, 7, 6, 223657, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='invitedmanager',
            name='expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
