# Generated by Django 5.1.5 on 2025-01-24 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_invitedmanager_created_at_invitedmanager_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitedmanager',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 24, 8, 25, 14, 428315, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitedmanager',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
