# Generated by Django 5.1.5 on 2025-01-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_contact_alter_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='preferred_position',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
