# Generated by Django 5.1.5 on 2025-02-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
