# Generated by Django 5.1.5 on 2025-01-27 03:50

import datetime
import django.db.models.deletion
import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0015_remove_player_preferred_position_delete_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Futsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=450)),
                ('location', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=games.models.get_next_friday)),
                ('time', models.TimeField(default=datetime.time(18, 0))),
                ('available_players', models.ManyToManyField(related_name='game_players', to='accounts.player')),
                ('futsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='games.futsal')),
            ],
        ),
    ]
