# Generated by Django 5.1.5 on 2025-01-27 04:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_player_preferred_position_delete_position'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='available_players',
            field=models.ManyToManyField(blank=True, null=True, related_name='game_players', to='accounts.player'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalsA', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('goalsB', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_complete', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='games.game')),
                ('teamA', models.ManyToManyField(blank=True, null=True, related_name='teamA', to='accounts.player')),
                ('teamB', models.ManyToManyField(blank=True, null=True, related_name='teamB', to='accounts.player')),
            ],
        ),
    ]
