# Generated by Django 5.1.5 on 2025-01-27 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_player_preferred_position_delete_position'),
        ('games', '0003_game_goalsa_game_goalsb_game_is_complete_game_teama_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='goals', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_goals', to='accounts.player')),
            ],
        ),
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assists', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_assists', to='accounts.player')),
                ('assist_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='games.goal')),
            ],
        ),
    ]
