# Generated by Django 5.1.5 on 2025-01-27 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_player_preferred_position_delete_position'),
        ('games', '0004_goal_assist'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='assist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='player_assists', to='accounts.player'),
        ),
        migrations.DeleteModel(
            name='Assist',
        ),
    ]
