# Generated by Django 5.1.5 on 2025-01-27 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_game_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('date', 'time', 'futsal')},
        ),
    ]
