# Generated by Django 5.1.5 on 2025-01-28 08:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_player_preferred_position_delete_position'),
        ('games', '0007_alter_game_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_player', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_game_rating', to='accounts.player')),
                ('rating_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_player', to='accounts.player')),
            ],
        ),
    ]
