# Generated by Django 5.1.5 on 2025-01-29 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_player_preferred_position_delete_position'),
        ('games', '0008_playerreviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerreviewrating',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_game_review_rating', to='accounts.player'),
        ),
        migrations.CreateModel(
            name='PlayerGameRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_rating', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_game_rating', to='accounts.player')),
            ],
        ),
    ]
