# Generated by Django 5.1.5 on 2025-01-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_playerreviewrating_player_playergamerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergamerating',
            name='rating',
            field=models.FloatField(default=5),
        ),
    ]
