# Generated by Django 5.1.5 on 2025-02-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_game_teamnamea_game_teamnameb'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='logoA',
            field=models.ImageField(blank=True, null=True, upload_to='team/logo/'),
        ),
        migrations.AddField(
            model_name='game',
            name='logoB',
            field=models.ImageField(blank=True, null=True, upload_to='team/logo/'),
        ),
    ]
